const assert=require('node:assert/strict');
const {Battle,C,overlaps,hullRay,distance,polar,sample}=require('../game.js');
let checks=0;const run=(b,n)=>{for(let i=0;i<n;i++)b.step();};
function check(name,fn){fn();checks++;console.log('PASS '+name);}
function isolated(){const b=new Battle('duel');b.start();b.moveFleet=()=>{};const own=b.fleets[0].ships[0],foe=b.fleets[1].ships[0];b.fleets[0].ships=[own];b.fleets[1].ships=[foe];Object.assign(own,{x:500,y:500,a:0,speed:0});Object.assign(foe,{x:500,y:300,a:0,speed:0});return b;}
check('Ready batteries fire in range and arc without player orders',()=>{const b=isolated();b.step();assert.equal(b.shots,6);assert.equal(b.fleets[0].ships[0].cool[0],120);assert.equal(b.fleets[0].ships[0].cool[1],0);b.step();assert.equal(b.shots,6);});
check('Enemy ahead or beyond engagement range does not trigger broadside',()=>{for(const p of [{x:750,y:500},{x:500,y:140}]){const b=isolated();Object.assign(b.fleets[1].ships[0],p);b.step();assert.equal(b.shots,0);}});
check('Port and starboard independently engage targets on both sides',()=>{const b=isolated(),foe=b.fleets[1].ships[0];b.fleets[1].ships.push({...foe,id:'1-2',y:700,cool:[0,0],flash:[0,0]});b.step();assert.equal(b.fleets[0].ships[0].cool[0],120);assert.equal(b.fleets[0].ships[0].cool[1],120);});
check('Friendly hulls mask guns; another clear target can still be engaged',()=>{const b=isolated(),own=b.fleets[0].ships[0];b.fleets[0].ships.push({...own,id:'0-2',y:370,cool:[120,120],flash:[0,0]});b.step();assert.equal(own.cool[0],0);assert.equal(own.hp,100);const foe=b.fleets[1].ships[0];b.fleets[1].ships.push({...foe,id:'1-2',x:550,cool:[120,120],flash:[0,0]});assert.equal(b.targetFor(own,0).id,'1-2');b.step();assert.ok(own.cool[0]>0);});
check('Raking geometry damages more deck fighting strength, not a fixed hull multiplier',()=>{const b=isolated(),s=b.fleets[0].ships[0];Object.assign(s,{x:0,y:0,a:0});const side={a:Math.PI/2,energy:1,travel:50},stern={a:0,energy:1,travel:50};const sideHit=hullRay(0,-100,0,200,s),sternHit=hullRay(-100,0,200,0,s);const A=b.damageForHit(side,s,sideHit),B=b.damageForHit(stern,s,sternHit);assert.ok(B.crew>A.crew);assert.equal(B.hull,A.hull);assert.ok(B.stern);assert.ok(B.rudder>0);});
check('Shot with residual energy can strike a second hull in the same step',()=>{const b=isolated();b.autoFire=()=>{};const a=b.fleets[1].ships[0],c={...a,id:'0-2',fleet:0,y:333,cool:[120,120],flash:[0,0]};Object.assign(a,{x:500,y:300,a:0});b.fleets[0].ships.push(c);b.balls=[{x:500,y:275,a:Math.PI/2,vx:0,vy:400,owner:'0-1',fleet:0,left:350,travel:0,energy:1,struckIds:new Set(['0-1'])}];b.step();assert.ok(a.hp<100);assert.ok(c.hp<100);assert.ok(b.events.some(e=>e.text.includes('Friendly fire')));});
function reposition(f,x,y,a){const s=f.ships[0];Object.assign(s,{x,y,a,s:0,speed:4});Object.assign(f,{x,y,a,s:0,path:Array.from({length:451},(_,i)=>{const t=-900+i*2;return {x:x+Math.cos(a)*t,y:y+Math.sin(a)*t,a,s:t};})});f.ships=[s];}
function collision(heading,seconds){const b=new Battle('duel');b.start();b.autoFire=()=>{};reposition(b.fleets[0],700,550,0);if(heading===Math.PI)reposition(b.fleets[1],830,550,heading);else reposition(b.fleets[1],770,470,heading);for(let i=0;i<60*seconds;i++){b.step();assert.ok(!overlaps(b.fleets[0].ships[0],b.fleets[1].ships[0]));}assert.ok(b.contacts.size>0);return b;}
check('Head-on hulls cannot pass through each other',()=>collision(Math.PI,8));
check('Crossing angled hulls stay non-overlapping through contact and backing',()=>collision(Math.PI/2,15));
check('A blocked follower queues rather than overlapping its predecessor',()=>{const b=new Battle('duel');b.start();b.autoFire=()=>{};const f=b.fleets[0];f.ships[0].rigging=0;run(b,900);for(let i=1;i<f.ships.length;i++)assert.ok(!overlaps(f.ships[i],f.ships[i-1]));assert.ok(f.ships[0].speed<2);});
check('Windward speed differs from reaching, and damage slows a ship',()=>{assert.equal(polar(C.windFrom),0);assert.equal(polar(0),1);const b=new Battle('duel');b.start();b.autoFire=()=>{};b.fleets[0].ships[0].rigging=10;run(b,150);assert.ok(b.fleets[0].ships[0].speed<2);});
check('Fighting strength can force surrender with an intact floating hull',()=>{const b=new Battle('duel');b.start();const f=b.fleets[0],positions=f.ships.slice(1).map(s=>({x:s.x,y:s.y}));f.ships[0].crew=10;b.removeSunk();assert.equal(f.ships.length,5);assert.equal(b.wrecks.length,1);assert.ok(!b.wrecks[0].sunk);f.ships.forEach((s,i)=>assert.equal(distance(s,positions[i]),0));});
check('Resignation works while paused, awards victory and freezes the battle',()=>{const b=new Battle();b.start();b.state='paused';assert.ok(b.resign(0));assert.equal(b.winner,1);assert.equal(b.reason,'resignation');const before=JSON.stringify(b.snapshot());run(b,60);assert.equal(JSON.stringify(b.snapshot()),before);});
check('Destroyed hulls sink; simultaneous defeat yields a draw',()=>{const b=new Battle('duel');b.start();for(const s of b.getShips())s.hp=0;b.removeSunk();assert.equal(b.state,'finished');assert.equal(b.winner,'draw');assert.ok(b.wrecks.every(s=>s.sunk));});
function match(){const b=new Battle();b.start();for(let i=0;i<60*600&&b.state==='playing';i++){b.ai(0);b.step();const ships=b.obstacles();for(let j=0;j<ships.length;j++){assert.ok(Number.isFinite(ships[j].x+ships[j].y+ships[j].a));for(let k=j+1;k<ships.length;k++)assert.ok(!overlaps(ships[j],ships[k]));}}assert.equal(b.state,'finished');return b;}
check('Complete battles retain solid hulls and deterministic outcomes',()=>{const a=match(),b=match();assert.equal(JSON.stringify(a.snapshot()),JSON.stringify(b.snapshot()));console.log('  Battle finished in '+a.realTime.toFixed(1)+' real seconds / '+(a.time/60).toFixed(1)+' simulated minutes.');});
console.log(checks+' meaningful checks passed.');
